package policy

import (
	"fmt"
	"os"
	"path/filepath"
)

// StarterPolicyYAML returns a commented, ready-to-edit default policy. It is
// itself a valid policy (default-deny) so `nockguard init` never scaffolds a
// file that fails to load — see TestStarterPolicyLoads.
func StarterPolicyYAML() string { return starterPolicy }

// WriteStarter writes the starter policy to path, creating parent directories as
// needed. It refuses to overwrite an existing file unless force is true, so a
// real policy is never clobbered by an accidental `init`. Returns true when a
// file was written.
func WriteStarter(path string, force bool) (bool, error) {
	if !force {
		switch _, err := os.Stat(path); {
		case err == nil:
			return false, fmt.Errorf("%s already exists (use --force to overwrite)", path)
		case !os.IsNotExist(err):
			return false, err
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(starterPolicy), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// starterPolicy is a valid, default-deny policy that demonstrates each control
// (allow, deny-precedence, approval gates, audit) with safe defaults and inline
// guidance. Editing it should be obvious; running it as-is is safe.
const starterPolicy = `# NockGuard policy — generated by ` + "`nockguard init`" + `.
# Docs: https://github.com/nocktechnologies/nockguard
#
# Model: DEFAULT-DENY. An agent may call only the tools its ` + "`allow`" + ` list
# matches. ` + "`deny`" + ` always wins over ` + "`allow`" + `. Patterns support ` + "`*`" + ` wildcards.

agents:
  # Rename "my-agent" to the --agent name you run the proxy as.
  my-agent:
    allow:
      - "*_list"      # read-only listing tools
      - "*_get"       # read-only fetch tools
      - "*_read"
    deny:
      - "*delete*"    # destructive tools are never allowed, even if an allow matched
      - "*_exec"
    # Phase 5: HOLD these for a human Approve/Deny before they run.
    # Opt-in — requires an approver wired (NOCKGUARD_APPROVAL_BOT_TOKEN + _CHAT_ID).
    require_approval:
      - "*kill_switch*"
      - "*spend*"

  # Unknown agents fall back to "default". mode: deny denies everything not
  # explicitly granted above — the safe baseline. Widen it deliberately, per agent.
  default:
    mode: deny

# Audit trail — opt-in. Uncomment to record every policy decision.
# audit:
#   enabled: true
#   path: ~/.nockguard/logs/audit.jsonl
#   # Tamper-evident (symmetric HMAC):
#   sign_key_env: NOCKGUARD_AUDIT_KEY
#   # Non-repudiable (asymmetric Ed25519) — run ` + "`nockguard keygen`" + ` first; takes precedence:
#   # sign_ed25519_key_env: NOCKGUARD_AUDIT_ED25519_KEY
#   # Stream enforcement decisions to the NockCC ops-log:
#   # forward:
#   #   enabled: true
#   #   url: https://cc.nocktechnologies.io
#   #   api_key_env: NOCKCC_API_KEY
`
